# Generated by Django 6.0.3 on 2026-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('projects', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
